RPRD-1638: Add support for Native media type and multi-format bid req…
streamrail/Prebid.js pull request #42
Opened 2024-12-10 14:27 UTC by michachen

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter  
- [x] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Add support for Native media type and multi-format bid requests in `index.js`,.
- Populate the changes on `rise/minutemedia/openweb/shinez/stn/BidAdapter.js`.
- Update all relevant `***BidAdapter_spec.js`.
- Update all relevant `***BidAdapter.md`.
- Keep backwards compatibility, Move `mimes` and `api` determination to VIDEO media type as its only relevant to video.

2024-12-10 14:28 UTC, michachen commented
https://risecodes.atlassian.net/browse/RPRD-1638

2024-12-10 14:52 UTC, michachen commented
As i see [here](https://github.com/streamrail/Prebid.js/blob/7f39411ee7294b09bf31bd31122f35b1788861bd/.github/workflows/jscpd.yml#L31) the threshold is 20. This tool was created on 08/06/2024. We have 5 adapters to maintain which will for-sure have duplicate code. Do you guys have any suggestions how to proceed? @lasloche @innay @george14051 @Gershon-Brainin @Dedis23

2024-12-22 11:38 UTC, george14051 commented on libraries/riseUtils/index.js
> +  const pos = getPos(bid)
add the ; syntax on each end of line please.

2024-12-22 11:38 UTC, george14051 commented on libraries/riseUtils/index.js
> +    bidObject.pos = pos
pos can be zero value, fix the if condition to pass also pos=0 (unknown position)

2024-12-22 12:28 UTC, Gershon-Brainin requested changes

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/constants.js
> +  { code: 'openwebxchange', gvlid: 280 }
Could you set it as a constant variable like `const OW_GVLID = 280;`?

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +  const firstMediaType = mediaTypes[0]
Please add the `;` at the end of the lines.

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +    return deepAccess(bidRequest, `mediaTypes.${firstMediaType}.name`)
Please add the `;` at the end of the line.

2024-12-22 12:28 UTC, Gershon-Brainin commented on modules/minutemediaBidAdapter.js
>    gvlid: 918,
Could you set it as a constant variable like `const MM_GVLID = 918;`?

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +  const firstMediaType = mediaTypes[0]
Please add the `;` at the end of the lines.

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +  const firstMediaType = mediaTypes[0]
Please add the `;` at the end of the lines.

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +  const pos = getPos(bid)
Please add the `;` at the end of the line.

2024-12-22 12:28 UTC, Gershon-Brainin commented on libraries/riseUtils/index.js
> +      bidObject.nativeOrtbRequest = nativeOrtbRequest
Please add the `;` at the end of the line.

2024-12-22 12:28 UTC, Gershon-Brainin commented on modules/openwebBidAdapter.js
>    gvlid: 280,
Could you set it as a constant variable like `const OW_GVLID = 280;`?

2024-12-23 09:59 UTC, Gershon-Brainin approved these changes

2024-12-29 10:22 UTC, george14051 approved these changes

2025-01-14 09:07 UTC, michachen commented
Prebid repo PR https://github.com/prebid/Prebid.js/pull/12653

2025-01-19 07:33 UTC, closed without merging